server:
  port: 8888

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql:///timegallery?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 20200401
    initialization-mode: always
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

logging:
  file:
    name: log/timegallery.log