server:
  port: 8888

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql:///timegallery?useUnicode=true&characterEncoding=UTF-8
    username: bill
    password: 20200401
  jpa:
    hibernate:
      ddl-auto: update
